var a = document.querySelector("span.a1")
a.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a.style.color = "black"
    a.style.backgroundColor = "lightgreen"
})
console.log(a)

var a2 = document.querySelector("span.a2")
a2.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a2.style.color = "black"
    a2.style.backgroundColor = "lightgreen"
})
console.log(a2)

var a3 = document.querySelector("span.a3")
a3.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a3.style.color = "black"
    a3.style.backgroundColor = "lightgreen"
})
console.log(a3)

var a4 = document.querySelector("span.a4")
a4.addEventListener("click", function () {

    console.log("Hi")
    // a.innerHTML="How Are you"
    a4.style.color = "black"
    a4.style.backgroundColor = "lightgreen"
})
console.log(a4)

var a5 = document.querySelector("span.a5")
a5.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a5.style.color = "black"
    a5.style.backgroundColor = "lightgreen"
})
console.log(a5)

var a6 = document.querySelector("span.a6")
a6.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a6.style.color = "black"
    a6.style.backgroundColor = "lightgreen"
})
console.log(a6)

var a7 = document.querySelector("span.a7")
a7.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a7.style.color = "black"
    a7.style.backgroundColor = "lightgreen"
})
console.log(a7)

var a8 = document.querySelector("span.a8")
a8.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a8.style.color = "black"
    a8.style.backgroundColor = "lightgreen"
})
console.log(a8)

var a9 = document.querySelector("span.a9")
a9.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a9.style.color = "black"
    a9.style.backgroundColor = "lightgreen"
})
console.log(a9)

var a10 = document.querySelector("span.a10")
a10.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a10.style.color = "black"
    a10.style.backgroundColor = "lightgreen"
})
console.log(a10)

var a11 = document.querySelector("span.a11")
a11.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a11.style.color = "black"
    a11.style.backgroundColor = "lightgreen"
})
console.log(a11)

var a12 = document.querySelector("span.a12")
a12.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a12.style.color = "black"
    a12.style.backgroundColor = "lightgreen"
})
console.log(a12)

var a13 = document.querySelector("span.a13")
a13.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a13.style.color = "black"
    a13.style.backgroundColor = "lightgreen"
})
console.log(a13)

var a14 = document.querySelector("span.a14")
a14.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a14.style.color = "black"
    a14.style.backgroundColor = "lightgreen"
})
console.log(a14)

var a15 = document.querySelector("span.a15")
a15.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a15.style.color = "black"
    a15.style.backgroundColor = "lightgreen"
})
console.log(a15)

var a16 = document.querySelector("span.a16")
console.log(a20)
a16.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a16.style.color = "black"
    a16.style.backgroundColor = "lightgreen"
})
console.log(a16)

var a17 = document.querySelector("span.a17")
a17.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a17.style.color = "black"
    a17.style.backgroundColor = "lightgreen"
})
console.log(a17)

var a18 = document.querySelector("span.a18")
a18.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a18.style.color = "black"
    a18.style.backgroundColor = "lightgreen"
})
console.log(a18)

var a19 = document.querySelector("span.a19")
a19.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a19.style.color = "black"
    a19.style.backgroundColor = "lightgreen"
})
console.log(a19)

var a20 = document.querySelector("span.a20")
a20.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    a20.style.color = "black"
    a20.style.backgroundColor = "lightgreen"
})

//                            WRONG OPTIONS

var wa11 = document.querySelector("span.wa11")
wa11.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa11.style.color = "black"
    wa11.style.backgroundColor = "hotpink"
})
console.log(wa11)

var wa12 = document.querySelector("span.wa12")
wa12.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa12.style.color = "black"
    wa12.style.backgroundColor = "hotpink"
})
console.log(wa12)

var wa13 = document.querySelector("span.wa13")
wa13.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa13.style.color = "black"
    wa13.style.backgroundColor = "hotpink"
})
console.log(wa13)

var wa21 = document.querySelector("span.wa21")
wa21.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa21.style.color = "black"
    wa21.style.backgroundColor = "hotpink"
})
console.log(wa21)

var wa22 = document.querySelector("span.wa22")
wa22.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa22.style.color = "black"
    wa22.style.backgroundColor = "hotpink"
})
console.log(wa22)

var wa23 = document.querySelector("span.wa23")
wa23.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa23.style.color = "black"
    wa23.style.backgroundColor = "hotpink"
})
console.log(wa23)

var wa31 = document.querySelector("span.wa31")
wa31.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa31.style.color = "black"
    wa31.style.backgroundColor = "hotpink"
})
console.log(wa31)

var wa32 = document.querySelector("span.wa32")
wa32.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa32.style.color = "black"
    wa32.style.backgroundColor = "hotpink"
})
console.log(wa32)

var wa33 = document.querySelector("span.wa33")
wa33.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa33.style.color = "black"
    wa33.style.backgroundColor = "hotpink"
})
console.log(wa33)

var wa41 = document.querySelector("span.wa41")
wa41.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa41.style.color = "black"
    wa41.style.backgroundColor = "hotpink"
})
console.log(wa41)

var wa42 = document.querySelector("span.wa42")
wa42.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa42.style.color = "black"
    wa42.style.backgroundColor = "hotpink"
})
console.log(wa42)

var wa43 = document.querySelector("span.wa43")
wa43.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa43.style.color = "black"
    wa43.style.backgroundColor = "hotpink"
})
console.log(wa43)

var wa51 = document.querySelector("span.wa51")
wa51.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa51.style.color = "black"
    wa51.style.backgroundColor = "hotpink"
})
console.log(wa51)

var wa52 = document.querySelector("span.wa52")
wa52.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa52.style.color = "black"
    wa52.style.backgroundColor = "hotpink"
})
console.log(wa52)

var wa53 = document.querySelector("span.wa53")
wa53.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa53.style.color = "black"
    wa53.style.backgroundColor = "hotpink"
})
console.log(wa53)

var wa61 = document.querySelector("span.wa61")
wa61.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa61.style.color = "black"
    wa61.style.backgroundColor = "hotpink"
})
console.log(wa61)

var wa62 = document.querySelector("span.wa62")
wa62.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa62.style.color = "black"
    wa62.style.backgroundColor = "hotpink"
})
console.log(wa62)

var wa63 = document.querySelector("span.wa63")
wa63.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa63.style.color = "black"
    wa63.style.backgroundColor = "hotpink"
})
console.log(wa63)

var wa71 = document.querySelector("span.wa71")
wa71.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa71.style.color = "black"
    wa71.style.backgroundColor = "hotpink"
})
console.log(wa71)

var wa72 = document.querySelector("span.wa72")
wa72.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa72.style.color = "black"
    wa72.style.backgroundColor = "hotpink"
})
console.log(wa72)

var wa73 = document.querySelector("span.wa73")
wa73.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa73.style.color = "black"
    wa73.style.backgroundColor = "hotpink"
})
console.log(wa73)

var wa81 = document.querySelector("span.wa81")
wa81.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa81.style.color = "black"
    wa81.style.backgroundColor = "hotpink"
})
console.log(wa81)

var wa82 = document.querySelector("span.wa82")
wa82.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa82.style.color = "black"
    wa82.style.backgroundColor = "hotpink"
})
console.log(wa82)

var wa83 = document.querySelector("span.wa83")
wa83.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa83.style.color = "black"
    wa83.style.backgroundColor = "hotpink"
})
console.log(wa83)

var wa91 = document.querySelector("span.wa91")
wa91.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa91.style.color = "black"
    wa91.style.backgroundColor = "hotpink"
})
console.log(wa91)

var wa92 = document.querySelector("span.wa92")
wa92.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa92.style.color = "black"
    wa92.style.backgroundColor = "hotpink"
})
console.log(wa92)

var wa93 = document.querySelector("span.wa93")
wa93.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa93.style.color = "black"
    wa93.style.backgroundColor = "hotpink"
})
console.log(wa93)

var wa101 = document.querySelector("span.wa101")
wa101.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa101.style.color = "black"
    wa101.style.backgroundColor = "hotpink"
})
console.log(wa101)

var wa102 = document.querySelector("span.wa102")
wa102.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa102.style.color = "black"
    wa102.style.backgroundColor = "hotpink"
})
console.log(wa102)

var wa103 = document.querySelector("span.wa103")
wa103.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa103.style.color = "black"
    wa103.style.backgroundColor = "hotpink"
})
console.log(wa103)

var wa111 = document.querySelector("span.wa111")
wa111.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa111.style.color = "black"
    wa111.style.backgroundColor = "hotpink"
})
console.log(wa111)

var wa112 = document.querySelector("span.wa112")
wa112.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa112.style.color = "black"
    wa112.style.backgroundColor = "hotpink"
})
console.log(wa112)

var wa113 = document.querySelector("span.wa113")
wa113.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa113.style.color = "black"
    wa113.style.backgroundColor = "hotpink"
})
console.log(wa113)

var wa121 = document.querySelector("span.wa121")
wa121.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa121.style.color = "black"
    wa121.style.backgroundColor = "hotpink"
})
console.log(wa121)

var wa122 = document.querySelector("span.wa122")
wa122.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa122.style.color = "black"
    wa122.style.backgroundColor = "hotpink"
})
console.log(wa122)

var wa123 = document.querySelector("span.wa123")
wa123.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa123.style.color = "black"
    wa123.style.backgroundColor = "hotpink"
})
console.log(wa123)

var wa131 = document.querySelector("span.wa131")
wa131.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa131.style.color = "black"
    wa131.style.backgroundColor = "hotpink"
})
console.log(wa131)

var wa132 = document.querySelector("span.wa132")
wa132.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa132.style.color = "black"
    wa132.style.backgroundColor = "hotpink"
})
console.log(wa132)

var wa133 = document.querySelector("span.wa133")
wa133.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa133.style.color = "black"
    wa133.style.backgroundColor = "hotpink"
})
console.log(wa133)

var wa141 = document.querySelector("span.wa141")
wa141.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa141.style.color = "black"
    wa141.style.backgroundColor = "hotpink"
})
console.log(wa141)

var wa142 = document.querySelector("span.wa142")
wa142.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa142.style.color = "black"
    wa142.style.backgroundColor = "hotpink"
})
console.log(wa142)

var wa143 = document.querySelector("span.wa143")
wa143.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa143.style.color = "black"
    wa143.style.backgroundColor = "hotpink"
})
console.log(wa143)

var wa151 = document.querySelector("span.wa151")
wa151.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa151.style.color = "black"
    wa151.style.backgroundColor = "hotpink"
})
console.log(wa151)

var wa152 = document.querySelector("span.wa152")
wa152.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa152.style.color = "black"
    wa152.style.backgroundColor = "hotpink"
})
console.log(wa152)

var wa153 = document.querySelector("span.wa153")
wa153.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa153.style.color = "black"
    wa153.style.backgroundColor = "hotpink"
})
console.log(wa153)

var wa161 = document.querySelector("span.wa161")
wa161.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa161.style.color = "black"
    wa161.style.backgroundColor = "hotpink"
})
console.log(wa161)

var wa162 = document.querySelector("span.wa162")
wa162.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa162.style.color = "black"
    wa162.style.backgroundColor = "hotpink"
})
console.log(wa162)

var wa163 = document.querySelector("span.wa163")
wa163.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa163.style.color = "black"
    wa163.style.backgroundColor = "hotpink"
})
console.log(wa163)

var wa171 = document.querySelector("span.wa171")
wa171.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa171.style.color = "black"
    wa171.style.backgroundColor = "hotpink"
})
console.log(wa171)

var wa172 = document.querySelector("span.wa172")
wa172.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa172.style.color = "black"
    wa172.style.backgroundColor = "hotpink"
})
console.log(wa172)

var wa173 = document.querySelector("span.wa173")
wa173.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa173.style.color = "black"
    wa173.style.backgroundColor = "hotpink"
})
console.log(wa173)

var wa181 = document.querySelector("span.wa181")
wa181.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa181.style.color = "black"
    wa181.style.backgroundColor = "hotpink"
})
console.log(wa181)

var wa182 = document.querySelector("span.wa182")
wa182.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa182.style.color = "black"
    wa182.style.backgroundColor = "hotpink"
})
console.log(wa182)

var wa183 = document.querySelector("span.wa183")
wa183.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa183.style.color = "black"
    wa183.style.backgroundColor = "hotpink"
})
console.log(wa183)

var wa191 = document.querySelector("span.wa191")
wa191.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa191.style.color = "black"
    wa191.style.backgroundColor = "hotpink"
})
console.log(wa191)

var wa192 = document.querySelector("span.wa192")
wa192.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa192.style.color = "black"
    wa192.style.backgroundColor = "hotpink"
})
console.log(wa192)

var wa193 = document.querySelector("span.wa193")
wa193.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa193.style.color = "black"
    wa193.style.backgroundColor = "hotpink"
})
console.log(wa193)

var wa201 = document.querySelector("span.wa201")
wa201.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa201.style.color = "black"
    wa201.style.backgroundColor = "hotpink"
})
console.log(wa201)

var wa202 = document.querySelector("span.wa202")
wa202.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa202.style.color = "black"
    wa202.style.backgroundColor = "hotpink"
})
console.log(wa202)

var wa203 = document.querySelector("span.wa203")
wa203.addEventListener("click", function () {
    console.log("Hi")
    // a.innerHTML="How Are you"
    wa203.style.color = "black"
    wa203.style.backgroundColor = "hotpink"
})
console.log(wa203)



// DARK MODE
var dark = document.querySelector("p.dark1")
dark.addEventListener("click", function () {
    if (document.body.style.backgroundColor == "gold"|| document.body.style.backgroundImage == "linear-gradient(45deg,darkgrey,grey,darkcyan)"||document.body.style.backgroundImage == "linear-gradient(45deg,rgb(102, 255, 0),blue,green)"||document.body.style.backgroundImage == "linear-gradient(cyan,lightgreen,gold)") {
        console.log("Hi")
        dark.innerHTML = "Night Mode"
        dark.style.color = "Black"
        dark.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundColor = "darkcyan"
        dark.style.width = "150px"
    }
    else if (document.body.style.backgroundColor == "darkcyan" ) {
        console.log("Hi")
        dark.innerHTML = "Normal Mode"
        dark.style.color = "Black"
        dark.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundColor = "lightpink"
        dark.style.width = "180px"
    }
    else {
        console.log("Hi")
        dark.innerHTML = "Comfort Mode"
        dark.style.color = "Black"
        dark.style.backgroundColor = "lightpink"
        dark.style.width = "190px"
        document.body.style.backgroundColor = "gold"
    }
})
console.log(dark)
// DARK MODE 2
var dark2 = document.querySelector("p.dark2")
dark2.addEventListener("click", function () {
    if (document.body.style.backgroundColor == "gold"||document.body.style.backgroundColor == "lightpink"||document.body.style.backgroundColor == "darkcyan"||dark2.innerHTML == "Comfort Mode") {
        console.log("Hi")
        dark2.innerHTML = "Night Mode"
        dark2.style.color = "Black"
        dark2.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "linear-gradient(45deg,darkgrey,grey,darkcyan)";
        dark2.style.width = "150px"
    }
    else if (dark2.innerHTML == "Night Mode" ) {
        console.log("Hi")
        dark2.innerHTML = "Normal Mode"
        dark2.style.color = "Black"
        dark2.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "linear-gradient(45deg,rgb(102, 255, 0),blue,green)"
        dark2.style.width = "180px"
    }
    else {
        console.log("Hi")
        dark2.innerHTML = "Comfort Mode"
        dark2.style.color = "Black"
        dark2.style.backgroundColor = "lightpink"
        dark2.style.width = "190px"
        document.body.style.backgroundImage = "linear-gradient(gold,lightgreen,cyan)"
    }
})
console.log(dark2)
// DARK MODE 3
var dark3 = document.querySelector("p.dark3")
dark3.addEventListener("click", function () {
    if (dark3.innerHTML == "Comfort Mode") {
        console.log("Hi")
        dark3.innerHTML = "Night Mode"
        dark3.style.color = "Black"
        dark3.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "url('Dark Bg.jpg')";
        document.body.style.backgroundSize = "100%";
        dark3.style.width = "150px"
    }
    else if (dark3.innerHTML == "Night Mode" ) {
        console.log("Hi")
        dark3.innerHTML = "Normal Mode"
        dark3.style.color = "Black"
        dark3.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "url('Quiz_img - Copy.webp')";
        dark3.style.width = "180px"
    }
    else {
        console.log("Hi")
        dark3.innerHTML = "Comfort Mode"
        dark3.style.color = "Black"
        dark3.style.backgroundColor = "lightpink"
        dark3.style.width = "190px"
        document.body.style.backgroundImage = "url('Comfort BG.jpeg')";        
        document.body.style.backgroundSize = "1600%";     // 1600% Done Deliberately not by mistake:)
    }
})
console.log(dark3)