var b1 = document.querySelector("span.a1")
var c1 = document.querySelector("span.wa11")
var d1 = document.querySelector("span.wa12")
var e1 = document.querySelector("span.wa13")
var f1 = document.querySelector("span.wa14")
b1.addEventListener("click", function () {
    b1.style.backgroundColor = "lightgreen"
    f1.innerHTML = "Correct Answer!!"
    f1.style.backgroundColor = "white"
    f1.style.color = "green"
})
c1.addEventListener("click", function () {
    b1.style.backgroundColor = "lightgreen"
    c1.style.backgroundColor = "hotpink"
    f1.innerHTML = "Wrong Answer!!"
    f1.style.backgroundColor = "white"
    f1.style.color = "red"
})
d1.addEventListener("click", function () {
    b1.style.backgroundColor = "lightgreen"
    d1.style.backgroundColor = "hotpink"
    f1.innerHTML = "Wrong Answer!!"
    f1.style.backgroundColor = "white"
    f1.style.color = "red"
})
e1.addEventListener("click", function () {
    b1.style.backgroundColor = "lightgreen"
    e1.style.backgroundColor = "hotpink"
    f1.innerHTML = "Wrong Answer!!"
    f1.style.backgroundColor = "white"
    f1.style.color = "red"
})
var b2 = document.querySelector("span.a2")
var c2 = document.querySelector("span.wa21")
var d2 = document.querySelector("span.wa22")
var e2 = document.querySelector("span.wa23")
var f2 = document.querySelector("span.wa24")
b2.addEventListener("click", function () {
    b2.style.backgroundColor = "lightgreen"
    f2.innerHTML = "Correct Answer!!"
    f2.style.backgroundColor = "white"
    f2.style.color = "green"
})
c2.addEventListener("click", function () {
    b2.style.backgroundColor = "lightgreen"
    c2.style.backgroundColor = "hotpink"
    f2.innerHTML = "Wrong Answer!!"
    f2.style.backgroundColor = "white"
    f2.style.color = "red"
})
d2.addEventListener("click", function () {
    b2.style.backgroundColor = "lightgreen"
    d2.style.backgroundColor = "hotpink"
    f2.innerHTML = "Wrong Answer!!"
    f2.style.backgroundColor = "white"
    f2.style.color = "red"
})
e2.addEventListener("click", function () {
    b2.style.backgroundColor = "lightgreen"
    e2.style.backgroundColor = "hotpink"
    f2.innerHTML = "Wrong Answer!!"
    f2.style.backgroundColor = "white"
    f2.style.color = "red"
})
var b3 = document.querySelector("span.a3")
var c3 = document.querySelector("span.wa31")
var d3 = document.querySelector("span.wa32")
var e3 = document.querySelector("span.wa33")
var f3 = document.querySelector("span.wa34")
b3.addEventListener("click", function () {
    b3.style.backgroundColor = "lightgreen"
    f3.innerHTML = "Correct Answer!!"
    f3.style.backgroundColor = "white"
    f3.style.color = "green"
})
c3.addEventListener("click", function () {
    b3.style.backgroundColor = "lightgreen"
    c3.style.backgroundColor = "hotpink"
    f3.innerHTML = "Wrong Answer!!"
    f3.style.backgroundColor = "white"
    f3.style.color = "red"
})
d3.addEventListener("click", function () {
    b3.style.backgroundColor = "lightgreen"
    d3.style.backgroundColor = "hotpink"
    f3.innerHTML = "Wrong Answer!!"
    f3.style.backgroundColor = "white"
    f3.style.color = "red"
})
e3.addEventListener("click", function () {
    b3.style.backgroundColor = "lightgreen"
    e3.style.backgroundColor = "hotpink"
    f3.innerHTML = "Wrong Answer!!"
    f3.style.backgroundColor = "white"
    f3.style.color = "red"
})
var b4 = document.querySelector("span.a4")
var c4 = document.querySelector("span.wa41")
var d4 = document.querySelector("span.wa42")
var e4 = document.querySelector("span.wa43")
var f4 = document.querySelector("span.wa44")
b4.addEventListener("click", function () {
    b4.style.backgroundColor = "lightgreen"
    f4.innerHTML = "Correct Answer!!"
    f4.style.backgroundColor = "white"
    f4.style.color = "green"
})
c4.addEventListener("click", function () {
    b4.style.backgroundColor = "lightgreen"
    c4.style.backgroundColor = "hotpink"
    f4.innerHTML = "Wrong Answer!!"
    f4.style.backgroundColor = "white"
    f4.style.color = "red"
})
d4.addEventListener("click", function () {
    b4.style.backgroundColor = "lightgreen"
    d4.style.backgroundColor = "hotpink"
    f4.innerHTML = "Wrong Answer!!"
    f4.style.backgroundColor = "white"
    f4.style.color = "red"
})
e4.addEventListener("click", function () {
    b4.style.backgroundColor = "lightgreen"
    e4.style.backgroundColor = "hotpink"
    f4.innerHTML = "Wrong Answer!!"
    f4.style.backgroundColor = "white"
    f4.style.color = "red"
})
var b5 = document.querySelector("span.a5")
var c5 = document.querySelector("span.wa51")
var d5 = document.querySelector("span.wa52")
var e5 = document.querySelector("span.wa53")
var f5 = document.querySelector("span.wa54")
b5.addEventListener("click", function () {
    b5.style.backgroundColor = "lightgreen"
    f5.innerHTML = "Correct Answer!!"
    f5.style.backgroundColor = "white"
    f5.style.color = "green"
})
c5.addEventListener("click", function () {
    b5.style.backgroundColor = "lightgreen"
    c5.style.backgroundColor = "hotpink"
    f5.innerHTML = "Wrong Answer!!"
    f5.style.backgroundColor = "white"
    f5.style.color = "red"
})
d5.addEventListener("click", function () {
    b5.style.backgroundColor = "lightgreen"
    d5.style.backgroundColor = "hotpink"
    f5.innerHTML = "Wrong Answer!!"
    f5.style.backgroundColor = "white"
    f5.style.color = "red"
})
e5.addEventListener("click", function () {
    b5.style.backgroundColor = "lightgreen"
    e5.style.backgroundColor = "hotpink"
    f5.innerHTML = "Wrong Answer!!"
    f5.style.backgroundColor = "white"
    f5.style.color = "red"
})
var b6 = document.querySelector("span.a6")
var c6 = document.querySelector("span.wa61")
var d6 = document.querySelector("span.wa62")
var e6 = document.querySelector("span.wa63")
var f6 = document.querySelector("span.wa64")
b6.addEventListener("click", function () {
    b6.style.backgroundColor = "lightgreen"
    f6.innerHTML = "Correct Answer!!"
    f6.style.backgroundColor = "white"
    f6.style.color = "green"
})
c6.addEventListener("click", function () {
    b6.style.backgroundColor = "lightgreen"
    c6.style.backgroundColor = "hotpink"
    f6.innerHTML = "Wrong Answer!!"
    f6.style.backgroundColor = "white"
    f6.style.color = "red"
})
d6.addEventListener("click", function () {
    b6.style.backgroundColor = "lightgreen"
    d6.style.backgroundColor = "hotpink"
    f6.innerHTML = "Wrong Answer!!"
    f6.style.backgroundColor = "white"
    f6.style.color = "red"
})
e6.addEventListener("click", function () {
    b6.style.backgroundColor = "lightgreen"
    e6.style.backgroundColor = "hotpink"
    f6.innerHTML = "Wrong Answer!!"
    f6.style.backgroundColor = "white"
    f6.style.color = "red"
})
var b7 = document.querySelector("span.a7")
var c7 = document.querySelector("span.wa71")
var d7 = document.querySelector("span.wa72")
var e7 = document.querySelector("span.wa73")
var f7 = document.querySelector("span.wa74")
b7.addEventListener("click", function () {
    b7.style.backgroundColor = "lightgreen"
    f7.innerHTML = "Correct Answer!!"
    f7.style.backgroundColor = "white"
    f7.style.color = "green"
})
c7.addEventListener("click", function () {
    b7.style.backgroundColor = "lightgreen"
    c7.style.backgroundColor = "hotpink"
    f7.innerHTML = "Wrong Answer!!"
    f7.style.backgroundColor = "white"
    f7.style.color = "red"
})
d7.addEventListener("click", function () {
    b7.style.backgroundColor = "lightgreen"
    d7.style.backgroundColor = "hotpink"
    f7.innerHTML = "Wrong Answer!!"
    f7.style.backgroundColor = "white"
    f7.style.color = "red"
})
e7.addEventListener("click", function () {
    b7.style.backgroundColor = "lightgreen"
    e7.style.backgroundColor = "hotpink"
    f7.innerHTML = "Wrong Answer!!"
    f7.style.backgroundColor = "white"
    f7.style.color = "red"
})
var b8 = document.querySelector("span.a8")
var c8 = document.querySelector("span.wa81")
var d8 = document.querySelector("span.wa82")
var e8 = document.querySelector("span.wa83")
var f8 = document.querySelector("span.wa84")
b8.addEventListener("click", function () {
    b8.style.backgroundColor = "lightgreen"
    f8.innerHTML = "Correct Answer!!"
    f8.style.backgroundColor = "white"
    f8.style.color = "green"
})
c8.addEventListener("click", function () {
    b8.style.backgroundColor = "lightgreen"
    c8.style.backgroundColor = "hotpink"
    f8.innerHTML = "Wrong Answer!!"
    f8.style.backgroundColor = "white"
    f8.style.color = "red"
})
d8.addEventListener("click", function () {
    b8.style.backgroundColor = "lightgreen"
    d8.style.backgroundColor = "hotpink"
    f8.innerHTML = "Wrong Answer!!"
    f8.style.backgroundColor = "white"
    f8.style.color = "red"
})
e8.addEventListener("click", function () {
    b8.style.backgroundColor = "lightgreen"
    e8.style.backgroundColor = "hotpink"
    f8.innerHTML = "Wrong Answer!!"
    f8.style.backgroundColor = "white"
    f8.style.color = "red"
})
var b9 = document.querySelector("span.a9")
var c9 = document.querySelector("span.wa91")
var d9 = document.querySelector("span.wa92")
var e9 = document.querySelector("span.wa93")
var f9 = document.querySelector("span.wa94")
b9.addEventListener("click", function () {
    b9.style.backgroundColor = "lightgreen"
    f9.innerHTML = "Correct Answer!!"
    f9.style.backgroundColor = "white"
    f9.style.color = "green"
})
c9.addEventListener("click", function () {
    b9.style.backgroundColor = "lightgreen"
    c9.style.backgroundColor = "hotpink"
    f9.innerHTML = "Wrong Answer!!"
    f9.style.backgroundColor = "white"
    f9.style.color = "red"
})
d9.addEventListener("click", function () {
    b9.style.backgroundColor = "lightgreen"
    d9.style.backgroundColor = "hotpink"
    f9.innerHTML = "Wrong Answer!!"
    f9.style.backgroundColor = "white"
    f9.style.color = "red"
})
e9.addEventListener("click", function () {
    b9.style.backgroundColor = "lightgreen"
    e9.style.backgroundColor = "hotpink"
    f9.innerHTML = "Wrong Answer!!"
    f9.style.backgroundColor = "white"
    f9.style.color = "red"
})
var b10 = document.querySelector("span.a10")
var c10 = document.querySelector("span.wa101")
var d10 = document.querySelector("span.wa102")
var e10 = document.querySelector("span.wa103")
var f10 = document.querySelector("span.wa104")
b10.addEventListener("click", function () {
    b10.style.backgroundColor = "lightgreen"
    f10.innerHTML = "Correct Answer!!"
    f10.style.backgroundColor = "white"
    f10.style.color = "green"
})
c10.addEventListener("click", function () {
    b10.style.backgroundColor = "lightgreen"
    c10.style.backgroundColor = "hotpink"
    f10.innerHTML = "Wrong Answer!!"
    f10.style.backgroundColor = "white"
    f10.style.color = "red"
})
d10.addEventListener("click", function () {
    b10.style.backgroundColor = "lightgreen"
    d10.style.backgroundColor = "hotpink"
    f10.innerHTML = "Wrong Answer!!"
    f10.style.backgroundColor = "white"
    f10.style.color = "red"
})
e10.addEventListener("click", function () {
    b10.style.backgroundColor = "lightgreen"
    e10.style.backgroundColor = "hotpink"
    f10.innerHTML = "Wrong Answer!!"
    f10.style.backgroundColor = "white"
    f10.style.color = "red"
})
var b11 = document.querySelector("span.a11")
var c11 = document.querySelector("span.wa111")
var d11 = document.querySelector("span.wa112")
var e11 = document.querySelector("span.wa113")
var f11 = document.querySelector("span.wa114")
b11.addEventListener("click", function () {
    b11.style.backgroundColor = "lightgreen"
    f11.innerHTML = "Correct Answer!!"
    f11.style.backgroundColor = "white"
    f11.style.color = "green"
})
c11.addEventListener("click", function () {
    b11.style.backgroundColor = "lightgreen"
    c11.style.backgroundColor = "hotpink"
    f11.innerHTML = "Wrong Answer!!"
    f11.style.backgroundColor = "white"
    f11.style.color = "red"
})
d11.addEventListener("click", function () {
    b11.style.backgroundColor = "lightgreen"
    d11.style.backgroundColor = "hotpink"
    f11.innerHTML = "Wrong Answer!!"
    f11.style.backgroundColor = "white"
    f11.style.color = "red"
})
e11.addEventListener("click", function () {
    b11.style.backgroundColor = "lightgreen"
    e11.style.backgroundColor = "hotpink"
    f11.innerHTML = "Wrong Answer!!"
    f11.style.backgroundColor = "white"
    f11.style.color = "red"
})
var b12 = document.querySelector("span.a12")
var c12 = document.querySelector("span.wa121")
var d12 = document.querySelector("span.wa122")
var e12 = document.querySelector("span.wa123")
var f12 = document.querySelector("span.wa124")
b12.addEventListener("click", function () {
    b12.style.backgroundColor = "lightgreen"
    f12.innerHTML = "Correct Answer!!"
    f12.style.backgroundColor = "white"
    f12.style.color = "green"
})
c12.addEventListener("click", function () {
    b12.style.backgroundColor = "lightgreen"
    c12.style.backgroundColor = "hotpink"
    f12.innerHTML = "Wrong Answer!!"
    f12.style.backgroundColor = "white"
    f12.style.color = "red"
})
d12.addEventListener("click", function () {
    b12.style.backgroundColor = "lightgreen"
    d12.style.backgroundColor = "hotpink"
    f12.innerHTML = "Wrong Answer!!"
    f12.style.backgroundColor = "white"
    f12.style.color = "red"
})
e12.addEventListener("click", function () {
    b12.style.backgroundColor = "lightgreen"
    e12.style.backgroundColor = "hotpink"
    f12.innerHTML = "Wrong Answer!!"
    f12.style.backgroundColor = "white"
    f12.style.color = "red"
})
var b13 = document.querySelector("span.a13")
var c13 = document.querySelector("span.wa131")
var d13 = document.querySelector("span.wa132")
var e13 = document.querySelector("span.wa133")
var f13 = document.querySelector("span.wa134")
b13.addEventListener("click", function () {
    b13.style.backgroundColor = "lightgreen"
    f13.innerHTML = "Correct Answer!!"
    f13.style.backgroundColor = "white"
    f13.style.color = "green"
})
c13.addEventListener("click", function () {
    b13.style.backgroundColor = "lightgreen"
    c13.style.backgroundColor = "hotpink"
    f13.innerHTML = "Wrong Answer!!"
    f13.style.backgroundColor = "white"
    f13.style.color = "red"
})
d13.addEventListener("click", function () {
    b13.style.backgroundColor = "lightgreen"
    d13.style.backgroundColor = "hotpink"
    f13.innerHTML = "Wrong Answer!!"
    f13.style.backgroundColor = "white"
    f13.style.color = "red"
})
e13.addEventListener("click", function () {
    b13.style.backgroundColor = "lightgreen"
    e13.style.backgroundColor = "hotpink"
    f13.innerHTML = "Wrong Answer!!"
    f13.style.backgroundColor = "white"
    f13.style.color = "red"
})
var b14 = document.querySelector("span.a14")
var c14 = document.querySelector("span.wa141")
var d14 = document.querySelector("span.wa142")
var e14 = document.querySelector("span.wa143")
var f14 = document.querySelector("span.wa144")
b14.addEventListener("click", function () {
    b14.style.backgroundColor = "lightgreen"
    f14.innerHTML = "Correct Answer!!"
    f14.style.backgroundColor = "white"
    f14.style.color = "green"
})
c14.addEventListener("click", function () {
    b14.style.backgroundColor = "lightgreen"
    c14.style.backgroundColor = "hotpink"
    f14.innerHTML = "Wrong Answer!!"
    f14.style.backgroundColor = "white"
    f14.style.color = "red"
})
d14.addEventListener("click", function () {
    b14.style.backgroundColor = "lightgreen"
    d14.style.backgroundColor = "hotpink"
    f14.innerHTML = "Wrong Answer!!"
    f14.style.backgroundColor = "white"
    f14.style.color = "red"
})
e14.addEventListener("click", function () {
    b14.style.backgroundColor = "lightgreen"
    e14.style.backgroundColor = "hotpink"
    f14.innerHTML = "Wrong Answer!!"
    f14.style.backgroundColor = "white"
    f14.style.color = "red"
})
var b15 = document.querySelector("span.a15")
var c15 = document.querySelector("span.wa151")
var d15 = document.querySelector("span.wa152")
var e15 = document.querySelector("span.wa153")
var f15 = document.querySelector("span.wa154")
b15.addEventListener("click", function () {
    b15.style.backgroundColor = "lightgreen"
    f15.innerHTML = "Correct Answer!!"
    f15.style.backgroundColor = "white"
    f15.style.color = "green"
})
c15.addEventListener("click", function () {
    b15.style.backgroundColor = "lightgreen"
    c15.style.backgroundColor = "hotpink"
    f15.innerHTML = "Wrong Answer!!"
    f15.style.backgroundColor = "white"
    f15.style.color = "red"
})
d15.addEventListener("click", function () {
    b15.style.backgroundColor = "lightgreen"
    d15.style.backgroundColor = "hotpink"
    f15.innerHTML = "Wrong Answer!!"
    f15.style.backgroundColor = "white"
    f15.style.color = "red"
})
e15.addEventListener("click", function () {
    b15.style.backgroundColor = "lightgreen"
    e15.style.backgroundColor = "hotpink"
    f15.innerHTML = "Wrong Answer!!"
    f15.style.backgroundColor = "white"
    f15.style.color = "red"
})
var b16 = document.querySelector("span.a16")
var c16 = document.querySelector("span.wa161")
var d16 = document.querySelector("span.wa162")
var e16 = document.querySelector("span.wa163")
var f16 = document.querySelector("span.wa164")
b16.addEventListener("click", function () {
    b16.style.backgroundColor = "lightgreen"
    f16.innerHTML = "Correct Answer!!"
    f16.style.backgroundColor = "white"
    f16.style.color = "green"
})
c16.addEventListener("click", function () {
    b16.style.backgroundColor = "lightgreen"
    c16.style.backgroundColor = "hotpink"
    f16.innerHTML = "Wrong Answer!!"
    f16.style.backgroundColor = "white"
    f16.style.color = "red"
})
d16.addEventListener("click", function () {
    b16.style.backgroundColor = "lightgreen"
    d16.style.backgroundColor = "hotpink"
    f16.innerHTML = "Wrong Answer!!"
    f16.style.backgroundColor = "white"
    f16.style.color = "red"
})
e16.addEventListener("click", function () {
    b16.style.backgroundColor = "lightgreen"
    e16.style.backgroundColor = "hotpink"
    f16.innerHTML = "Wrong Answer!!"
    f16.style.backgroundColor = "white"
    f16.style.color = "red"
})
var b17 = document.querySelector("span.a17")
var c17 = document.querySelector("span.wa171")
var d17 = document.querySelector("span.wa172")
var e17 = document.querySelector("span.wa173")
var f17 = document.querySelector("span.wa174")
b17.addEventListener("click", function () {
    b17.style.backgroundColor = "lightgreen"
    f17.innerHTML = "Correct Answer!!"
    f17.style.backgroundColor = "white"
    f17.style.color = "green"
})
c17.addEventListener("click", function () {
    b17.style.backgroundColor = "lightgreen"
    c17.style.backgroundColor = "hotpink"
    f17.innerHTML = "Wrong Answer!!"
    f17.style.backgroundColor = "white"
    f17.style.color = "red"
})
d17.addEventListener("click", function () {
    b17.style.backgroundColor = "lightgreen"
    d17.style.backgroundColor = "hotpink"
    f17.innerHTML = "Wrong Answer!!"
    f17.style.backgroundColor = "white"
    f17.style.color = "red"
})
e17.addEventListener("click", function () {
    b17.style.backgroundColor = "lightgreen"
    e17.style.backgroundColor = "hotpink"
    f17.innerHTML = "Wrong Answer!!"
    f17.style.backgroundColor = "white"
    f17.style.color = "red"
})
var b18 = document.querySelector("span.a18")
var c18 = document.querySelector("span.wa181")
var d18 = document.querySelector("span.wa182")
var e18 = document.querySelector("span.wa183")
var f18 = document.querySelector("span.wa184")
b18.addEventListener("click", function () {
    b18.style.backgroundColor = "lightgreen"
    f18.innerHTML = "Correct Answer!!"
    f18.style.backgroundColor = "white"
    f18.style.color = "green"
})
c18.addEventListener("click", function () {
    b18.style.backgroundColor = "lightgreen"
    c18.style.backgroundColor = "hotpink"
    f18.innerHTML = "Wrong Answer!!"
    f18.style.backgroundColor = "white"
    f18.style.color = "red"
})
d18.addEventListener("click", function () {
    b18.style.backgroundColor = "lightgreen"
    d18.style.backgroundColor = "hotpink"
    f18.innerHTML = "Wrong Answer!!"
    f18.style.backgroundColor = "white"
    f18.style.color = "red"
})
e18.addEventListener("click", function () {
    b18.style.backgroundColor = "lightgreen"
    e18.style.backgroundColor = "hotpink"
    f18.innerHTML = "Wrong Answer!!"
    f18.style.backgroundColor = "white"
    f18.style.color = "red"
})
var b19 = document.querySelector("span.a19")
var c19 = document.querySelector("span.wa191")
var d19 = document.querySelector("span.wa192")
var e19 = document.querySelector("span.wa193")
var f19 = document.querySelector("span.wa194")
b19.addEventListener("click", function () {
    b19.style.backgroundColor = "lightgreen"
    f19.innerHTML = "Correct Answer!!"
    f19.style.backgroundColor = "white"
    f19.style.color = "green"
})
c19.addEventListener("click", function () {
    b19.style.backgroundColor = "lightgreen"
    c19.style.backgroundColor = "hotpink"
    f19.innerHTML = "Wrong Answer!!"
    f19.style.backgroundColor = "white"
    f19.style.color = "red"
})
d19.addEventListener("click", function () {
    b19.style.backgroundColor = "lightgreen"
    d19.style.backgroundColor = "hotpink"
    f19.innerHTML = "Wrong Answer!!"
    f19.style.backgroundColor = "white"
    f19.style.color = "red"
})
e19.addEventListener("click", function () {
    b19.style.backgroundColor = "lightgreen"
    e19.style.backgroundColor = "hotpink"
    f19.innerHTML = "Wrong Answer!!"
    f19.style.backgroundColor = "white"
    f19.style.color = "red"
})
var b20 = document.querySelector("span.a20")
var c20 = document.querySelector("span.wa201")
var d20 = document.querySelector("span.wa202")
var e20 = document.querySelector("span.wa203")
var f20 = document.querySelector("span.wa204")
b20.addEventListener("click", function () {
    b20.style.backgroundColor = "lightgreen"
    f20.innerHTML = "Correct Answer!!"
    f20.style.backgroundColor = "white"
    f20.style.color = "green"
})
c20.addEventListener("click", function () {
    b20.style.backgroundColor = "lightgreen"
    c20.style.backgroundColor = "hotpink"
    f20.innerHTML = "Wrong Answer!!"
    f20.style.backgroundColor = "white"
    f20.style.color = "red"
})
d20.addEventListener("click", function () {
    b20.style.backgroundColor = "lightgreen"
    d20.style.backgroundColor = "hotpink"
    f20.innerHTML = "Wrong Answer!!"
    f20.style.backgroundColor = "white"
    f20.style.color = "red"
})
e20.addEventListener("click", function () {
    b20.style.backgroundColor = "lightgreen"
    e20.style.backgroundColor = "hotpink"
    f20.innerHTML = "Wrong Answer!!"
    f20.style.backgroundColor = "white"
    f20.style.color = "red"
})
// DARK MODE
var dark = document.querySelector("p.dark1")
dark.addEventListener("click", function () {
    if (document.body.style.backgroundColor == "gold" || document.body.style.backgroundImage == "linear-gradient(45deg,darkgrey,grey,darkcyan)" || document.body.style.backgroundImage == "linear-gradient(45deg,rgb(102, 255, 0),blue,green)" || document.body.style.backgroundImage == "linear-gradient(cyan,lightgreen,gold)") {
        console.log("Hi")
        dark.innerHTML = "Night Mode"
        dark.style.color = "Black"
        dark.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundColor = "darkcyan"
        dark.style.width = "150px"
    }
    else if (document.body.style.backgroundColor == "darkcyan") {
        console.log("Hi")
        dark.innerHTML = "Normal Mode"
        dark.style.color = "Black"
        dark.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundColor = "lightpink"
        dark.style.width = "180px"
    }
    else {
        console.log("Hi")
        dark.innerHTML = "Comfort Mode"
        dark.style.color = "Black"
        dark.style.backgroundColor = "lightpink"
        dark.style.width = "190px"
        document.body.style.backgroundColor = "gold"
    }
})
console.log(dark)
// DARK MODE 2
var dark2 = document.querySelector("p.dark2")
dark2.addEventListener("click", function () {
    if (document.body.style.backgroundColor == "gold" || document.body.style.backgroundColor == "lightpink" || document.body.style.backgroundColor == "darkcyan" || dark2.innerHTML == "Comfort Mode") {
        console.log("Hi")
        dark2.innerHTML = "Night Mode"
        dark2.style.color = "Black"
        dark2.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "linear-gradient(45deg,darkgrey,grey,darkcyan)";
        dark2.style.width = "150px"
    }
    else if (dark2.innerHTML == "Night Mode") {
        console.log("Hi")
        dark2.innerHTML = "Normal Mode"
        dark2.style.color = "Black"
        dark2.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "linear-gradient(45deg,rgb(102, 255, 0),blue,green)"
        dark2.style.width = "180px"
    }
    else {
        console.log("Hi")
        dark2.innerHTML = "Comfort Mode"
        dark2.style.color = "Black"
        dark2.style.backgroundColor = "lightpink"
        dark2.style.width = "190px"
        document.body.style.backgroundImage = "linear-gradient(gold,lightgreen,cyan)"
    }
})
console.log(dark2)
// DARK MODE 3
var dark3 = document.querySelector("p.dark3")
dark3.addEventListener("click", function () {
    if (dark3.innerHTML == "Comfort Mode") {
        console.log("Hi")
        dark3.innerHTML = "Night Mode"
        dark3.style.color = "Black"
        dark3.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "url('Dark Bg.jpg')";
        document.body.style.backgroundSize = "100%";
        dark3.style.width = "150px"
    }
    else if (dark3.innerHTML == "Night Mode") {
        console.log("Hi")
        dark3.innerHTML = "Normal Mode"
        dark3.style.color = "Black"
        dark3.style.backgroundColor = "lightseagreen"
        document.body.style.backgroundImage = "url('Quiz_img - Copy.webp')";
        dark3.style.width = "180px"
    }
    else {
        console.log("Hi")
        dark3.innerHTML = "Comfort Mode"
        dark3.style.color = "Black"
        dark3.style.backgroundColor = "lightpink"
        dark3.style.width = "190px"
        document.body.style.backgroundImage = "url('Comfort BG.jpeg')";
        document.body.style.backgroundSize = "1600%";     // 1600% Done Deliberately not by mistake:)
    }
})
console.log(dark3)
